feat: add lvl option to custom spawn command and some default params
decaprime/CommunityCommands pull request #15
Opened 2023-07-27 14:16 UTC by robotomist

This pr simply adds a level option for the customspawn command
It also adds some default params to other options for convenience.

There is no check for negative level values values because the game seems to already be doing it. Setting level to anything under 0 creates a unit of level 0

2023-07-27 14:17 UTC, robotomist commented on Commands/SpawnNpcCommands.cs
> +				return new(name, new(id));
everything above is just formatter deleting editing spaces

2023-07-27 16:33 UTC, decaprime requested changes

2023-07-27 16:33 UTC, decaprime commented on Commands/SpawnNpcCommands.cs
> +	public static void CustomSpawnNpc(ChatCommandContext ctx, CharacterUnit unit, int level = 0, BloodType type = BloodType.Frailed, int quality = 0, bool consumable = true, int duration = -1)
Prefer to not reorder the existing parameters. Motivation being some have saved snippets/macros based expecting the existing order.

VCF doesn't (yet) have the ability to specify specific named optional arguments as you would in a C# call (i.e. `.customspawn quality=50 level=100` etc.

2023-07-27 16:33 UTC, decaprime commented on Commands/SpawnNpcCommands.cs
> +			unitLevel.Level = level;
What happens if you set level to 0? If it's looking like a default behavior have you tested interaction, i.e. spawn-> see numbers in fight -> kill->expected loot to double check behavior as expected.

Alternatively you can avoid the consequence of setting default by passing level in as `int? level = null` then if the value isn't present then don't mutate UnitLevel component at all.

2023-07-27 16:33 UTC, decaprime commented on Commands/SpawnNpcCommands.cs
> +			unitLevel.Level = level;
I read PR as < 0, but explicitly what does setting level = 0 do? I think not specifying the parameter the unit should spawn like it did in the previous version of the command and not at level 0.

2023-07-27 17:16 UTC, robotomist commented on Commands/SpawnNpcCommands.cs
> +			unitLevel.Level = level;
Setting level = 0, spawns unit with  level 0 I tested it on a bomber and a thug both dropped loot correctly. I'll put lvl at the end so it doesn't change order for pre-existing macros. Should I leave the new defaults for blood type etc in or just set it back to what it was before?

2023-07-27 17:17 UTC, robotomist commented on Commands/SpawnNpcCommands.cs
> +	public static void CustomSpawnNpc(ChatCommandContext ctx, CharacterUnit unit, int level = 0, BloodType type = BloodType.Frailed, int quality = 0, bool consumable = true, int duration = -1)
oh good point didn't think of that

2023-07-27 17:20 UTC, robotomist commented on Commands/SpawnNpcCommands.cs
> +			unitLevel.Level = level;
Oh does loot get affected by level? I actually will need to confirm that, both dropped loot but I'm not sure if level should scale what/amount of loot is dropped

2023-07-28 16:11 UTC, robotomist commented on Commands/SpawnNpcCommands.cs
> +	public static void CustomSpawnNpc(ChatCommandContext ctx, CharacterUnit unit, int level = 0, BloodType type = BloodType.Frailed, int quality = 0, bool consumable = true, int duration = -1)
> Prefer to not reorder the existing parameters. Motivation being some have saved snippets/macros based expecting the existing order.
> 
> VCF doesn't (yet) have the ability to specify specific named optional arguments as you would in a C# call (i.e. `.customspawn quality=50 level=100` etc.

moved to the end and edited the description

2023-08-06 04:21 UTC, decaprime commented
Thanks for this contribution @robotomist !

2023-08-06 04:21 UTC, decaprime approved these changes

2023-08-06 04:40 UTC, merged